project:
  type: book
  execute-dir: project

execute:
  freeze: auto
  # cache: true
  
  
book:
  title: "MQAT"
  output-file: "QMAT_Rexercises"
  subtitle: "Exercises in R"
  author: 
    - name: "Rosa Félix"
      email: rosamfelix@tecnico.pt
      url: https://www.rosafelix.bike
      orcid: 0000-0002-5642-6006
      # affiliation: "Instituto Superior Técnico - University of Lisbon"
    - name: "Gabriel Valença"
      email: gabrielvalenca@tecnico.pt
      url: https://ushift.tecnico.ulisboa.pt/team-gabriel-valenca/
      orcid: 0000-0002-3684-3005
      # affiliation: "Instituto Superior Técnico - University of Lisbon"
    - name: "Filipe Moura"
      email: fmoura@tecnico.pt
      url: https://ushift.tecnico.ulisboa.pt/team-filipe-moura/
      orcid: 0000-0001-7749-8490
  date: today
  # date-modified: today
  chapters:
    - index.qmd
    - software.qmd
    - part: "**Data and Models**"
      chapters:
        - r-basics.qmd
        - data-manipulation.qmd
        - eda.qmd
        - linear-regression.qmd
        - factor-analysis.qmd
        - clusters.qmd
    - part: "**GIS in R**"
      chapters:
        - spatial-data.qmd
        - interactive-maps.qmd
        - centroids.qmd
        # - geocode.qmd
        - desire-lines.qmd
        - distances.qmd
        - buffers.qmd
        - open-data.qmd
        - grid.qmd
        # - quarto/r5r.qmd
        # - intro.qmd
    # - about.qmd
    - references.qmd
  
  repo-url: https://github.com/U-Shift/MQAT
  site-url: https://U-Shift.github.io/MQAT
  # favicon: images/favicon.png
  sidebar:
    tools:
    - icon: download
      href: https://github.com/U-Shift/MQAT/releases/download/2025/QMAT_RGIS_Exercises_2025.pdf
      text: "Download PDF"
      target: _blank
  page-footer:
    left: "R Félix, G Valença, F Moura"
    center: "MQAT - Instituto Superior Técnico"
    right: "September 2025"
    
    
bibliography: references.bib
link-citations: true
citeproc: true 


format:
  html:
    theme:
      light: cosmo
      dark: superhero
    code-fold: show
    code-tools: true
    number-depth: 3
    toc-expand: 3
  pdf:
   # documentclass: scrreprt
   documentclass: scrbook # para abrir páginas pares e impares, e heading no topo.
   geometry:
      - inner=3cm
      - outer=3cm
      - top=3cm
      - bottom=4cm
   # engine: knitr
   papersize: A4
   fig-align: center # does not work!
   # fig-asp: 1
   toc: true
   number-depth: 3
   toc-depth: 3
   color-links: true
   linkcolor: blue
   citecolor: black
   urlcolor: blue
   code-overflow: wrap # does not work! use next lines instead
   include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \raggedbottom
        \usepackage[automark]{scrlayer-scrpage}
        \automark[chapter]{chapter}
# raggedbottom prevents stretching vertical spaces to fill the page height
# Use chapter titles only in the header with automark
#    output-ext:  "pdf"
prefer-html: true
    
editor: visual

google-scholar: true
